services:
  - type: web
    name: multilingual-voice-assistant
    env: python  # Specifies Python backend
    buildCommand: pip install -r requirements.txt  # Install dependencies
    startCommand: python app.py  # Start the Flask app
    envVars:
      - key: FLASK_ENV
        value: production
    regions:
      - oregon  # Define the deployment region
