services:
  - type: web
    name: multilingual-voice-assistant
    runtime: python  # Preferred over 'env' for clarity
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon  # Use 'region', not 'regions' unless you specify multiple
